name: ci

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        run: yarn
      - name: Install and build
        run: yarn --frozen-lockfile
      - name: Unit tests
      - run: yarn test:ci
      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: |
            junit.xml
            coverage
