name: ci-pr-report
on:
  workflow_run:
    workflows: ['ci-pr-test']
    types:
      - completed
jobs:
  test-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Process Test Results
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Jest Tests
          path: 'junit.xml'
          reporter: jest-junit
  coverage-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci-pr-test.yml
          name: test-results
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/coverage-final.json
