name: ci-pr-test

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: |
          echo $PR_NUM > ./pr_num.txt
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and build
        run: yarn --frozen-lockfile
      - name: Unit tests
        run: yarn test:ci
      - name: Upload test-results artifact
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: |
            pr_num.txt
            junit.xml
            coverage
