name: coverage-report
on:
  workflow_run:
    workflows: ['ci']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: ./coverage/cobertura-coverage.xml
          flags: unittests
          name: cobertura-coverage
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
