name: test-report
on:
  workflow_run:
    workflows: ['ci']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: JEST Tests
          path: 'junit.xml'
          reporter: jest-junit
      - name: Unzip the artifact
        run: unzip test-results.zip
      - name: List structure of artifacts
        run: ls -R
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
